apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: default
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: vol-secret
          secret:
            secretName: mysecret	
      containers:
        - name: container-alpine
          image: alpine:3.7
          command: ["bin/sh","-c","sleep 3600"]
          volumeMounts:
            - name: vol-secret
              mountPath: /secret        
