apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: default
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-conf
          configMap:
            name: redis-config
      containers:
        - name: container-redis
          image: redis:6.2
          ports:
            - containerPort: 6379          
          volumeMounts:
            - name: redis-conf
              mountPath: /etc/config
          command: ["redis-server","/etc/config/redis.conf"]			  