apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: nfs-pvc
      spec:
        resources:
          requests:
            storage: 500Mi
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs-csi       
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:       
        - name: container-nginx
          image: nginx:1.26.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nfs-pvc
              mountPath: /usr/share/nginx/html
  
