apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: default
  labels:
    pv: nfs-pvc
spec:
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadOnlyMany
  selector:
    matchLabels:
      pv: nfs-pv1