name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs/
            includes/
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ github.run_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-git-committers-plugin-2
          pip install markdown-callouts
          pip install mkdocs-rss-plugin
          pip install pymdown-extensions
          pip install mkdocs-encryptcontent-plugin
          pip install mkdocs-material
      - name: Deploy to GitHub Pages
        run: |
          if [ -d "docs" ]; then
            echo "Docs directory exists. Proceeding with deployment."
            mkdocs gh-deploy --force
          else
            echo "Docs directory does not exist. Deployment aborted."
            exit 1
          fi